"""Assemble Artillery configs from modular scenario files.

Reads config.yml + scenarios/*.yml (multi-document YAML with per-scenario
arrivalRate), groups scenarios by rate, and writes one artillery_{rate}rps.yml
per unique rate.  Prints generated file paths to stdout (consumed by run.sh).
"""

import copy
from collections import defaultdict
from pathlib import Path

import yaml

PERF_DIR = Path(__file__).resolve().parent
CONFIG_PATH = PERF_DIR / "config.yml"
SCENARIOS_DIR = PERF_DIR / "scenarios"

HEADER = "# GENERATED by assemble.py — do not edit manually\n"


def assemble() -> None:
    base_config = yaml.safe_load(CONFIG_PATH.read_text())

    # group flow steps by arrivalRate
    groups: dict[int, list] = defaultdict(list)

    for scenario_file in sorted(SCENARIOS_DIR.glob("*.yml")):
        docs = list(yaml.safe_load_all(scenario_file.read_text()))
        if len(docs) < 2:
            raise ValueError(
                f"{scenario_file.name}: expected two YAML documents "
                "(metadata + flow steps)"
            )
        meta, steps = docs[0], docs[1]
        if not isinstance(meta, dict) or "arrivalRate" not in meta:
            raise ValueError(
                f"{scenario_file.name}: first document must contain 'arrivalRate'"
            )
        rate = int(meta["arrivalRate"])
        if isinstance(steps, list):
            groups[rate].extend(steps)

    for rate in sorted(groups):
        config = copy.deepcopy(base_config)
        config["config"]["phases"][0]["arrivalRate"] = rate
        config["scenarios"] = [{"name": "Full API coverage", "flow": groups[rate]}]

        output_path = PERF_DIR / f"artillery_{rate}rps.yml"
        output = yaml.dump(config, default_flow_style=False, sort_keys=False)
        output_path.write_text(HEADER + output)
        print(output_path)


if __name__ == "__main__":
    assemble()
